pub const MAX_MAP_WIDTH: i32 = 80;
pub const MAX_MAP_HEIGHT: i32 = 80;
pub const MAP_MAX_TILES = MAX_MAP_WIDTH * MAX_MAP_HEIGHT;

pub const UI_CELLS_PIPS: i32 = 2;
pub const UI_CELLS_BOTTOM: i32 = 11;

pub const MAP_AREA_CELLS_WIDTH: i32 = 44;
pub const MAP_AREA_CELLS_HEIGHT: i32 = 20;

pub const SCREEN_CELLS_WIDTH: i32 = MAP_AREA_CELLS_WIDTH;
pub const SCREEN_CELLS_HEIGHT: i32 = MAP_AREA_CELLS_HEIGHT + UI_CELLS_PIPS + UI_CELLS_BOTTOM;
